### ISSUE TITLE
Error handling for "Create a checkout session using Stripe hosted Checkout page"

### ISSUE THREAD

**Issue by shaklev** [oscarychen/drf-stripe-subscription#1]
Firstly big ups for the library !

In regards to the error, `my-site.com/stripe/checkout/` route is missing some error handling ( it doesn't return a proper JSON response if `price_id` is missing or the value is incorrect , but returns 500 Internal Server Error ).

**Comment by oscarychen** [comment]
@shaklev Thanks for catching that. I added error handling to this view & endpoint now. See: https://github.com/oscarychen/drf-stripe-subscription/releases/tag/1.1.6
