### ISSUE TITLE
Invalid field name(s) for model CustomUser: 'username'  while trying to pull new  data from stripe

### ISSUE THREAD

**Issue by anirbanchakraborty123** [oscarychen/drf-stripe-subscription#18]
Invalid field name(s) for model CustomUser: 'username'

>> python manage.py update_stripe_customers

Updated Stripe Customer cus_LSr9w7FB2J7r9U
Updated Stripe Customer cus_LSN6YXRJULxYv2
Updated Stripe Customer cus_LSLsozLd7PpiAJ
Updated Stripe Customer cus_LSLoxRY2x62iqT
Updated Stripe Customer cus_LSBn1ocYarYb8I
Updated Stripe Customer cus_LSBMjVw45wQLc9
Updated Stripe Customer cus_LS8UsIDLMRgQL9
Traceback (most recent call last):
  File "C:\backend\env\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "C:\backend\env\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
accounts.models.CustomUser.DoesNotExist: CustomUser matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\backend\mrbackend\manage.py", line 22, in <module>
    main()
  File "C:\backend\mrbackend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\backend\env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line 
    utility.execute()
  File "C:\backend\env\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\backend\env\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\backend\env\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\backend\env\lib\site-packages\drf_stripe\management\commands\update_stripe_customers.py", line 14, in handle
    stripe_api_update_customers(limit=kwargs.get('limit'), starting_after=kwargs.get('starting_after'))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\backend\env\lib\site-packages\drf_stripe\stripe_api\customers.py", line 159, in stripe_api_update_customers
    user, user_created = get_user_model().objects.get_or_create(
  File "C:\backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\backend\env\lib\site-packages\django\db\models\query.py", line 583, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
  File "C:\backend\env\lib\site-packages\django\db\models\query.py", line 634, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model CustomUser: 'username'.

my customuser model:

class CustomUser(AbstractUser):
     username = None
    email = models.EmailField(_('email address'), unique=True)
    bio = models.TextField()
    gender = models.CharField(
        max_length=140,
        null=True,
        choices=(
            ('Male', 'Male'),
            ('Female', 'Female'),
            ('Other', 'Other')
        )
    )
    birth_date = models.DateField(null=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

Please help me resolve the issue.ASAP

**Comment by oscarychen** [comment]
Are you using a customized user model with different model attributes?

**Comment by anirbanchakraborty123** [comment]
yes...heere is my custom model

class CustomUser(AbstractUser):
    """
    A User model that uses `email` as it's default identifier instead of
    username.
    """
    class Types(models.TextChoices):
        CANDIDATE = "CANDIDATE", "Candidate"
        EMPLOYER = "EMPLOYER", "Employer"

    base_type = Types.CANDIDATE
    type = models.CharField(
        _("Type"), max_length=50, choices=Types.choices, default=base_type
    )
username=None # THIS CODE IS GIVING ISSUE
    email = models.EmailField(_('email address'), unique=True)
    bio = models.TextField()
    gender = models.CharField(
        max_length=140,
        null=True,
        choices=(
            ('Male', 'Male'),
            ('Female', 'Female'),
            ('Other', 'Other')
        )
    )
    birth_date = models.DateField(null=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=
False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = managers.CustomUserManager()

    def __str__(self):
        return self.email

class CandidateManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=CustomUser.
Types.CANDIDATE)

class EmployerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=CustomUser.
Types.EMPLOYER)

class Candidate(CustomUser):
    base_type = CustomUser.Types.CANDIDATE
    objects = CandidateManager()

    class Meta:
        proxy = True

class Employer(CustomUser):
    base_type = CustomUser.Types.EMPLOYER
    objects = EmployerManager()

**Comment by anirbanchakraborty123** [comment]
Please  let me know the solution.I need it asap please.

**Comment by oscarychen** [comment]
Can you wait till the weekend?
I need to add a setting so that you can specify a custom field to use to reference the user model instead of the default username, in which case you can use email or another field.

**Comment by oscarychen** [comment]
@anirbanchakraborty123 [V1.1.11](https://github.com/oscarychen/drf-stripe-subscription/releases/tag/1.1.11) added support for custom Django User, it should work for your use case.

**Comment by anirbanchakraborty123** [comment]
Hey Oscar, First of  all Thank you for the wonderful library, Secondly, Can
you please do it as early as possible because I need to launch it live
before the weekend.Otherwise client will get frustrated.
Thank you.

**Comment by oscarychen** [comment]
@anirbanchakraborty123 is this not it? https://github.com/oscarychen/drf-stripe-subscription/releases/tag/1.1.11
