### ISSUE TITLE
Please allow all the params in _make_stripe_checkout_params be set in settings

### ISSUE THREAD

**Issue by joshuakoh1** [oscarychen/drf-stripe-subscription#2]
Hello,

Great work here! Small request, please allow all of the parameters sent to stripe checkout session be set in settings!

Thank you

**Comment by oscarychen** [comment]
What are some of the parameters you would like to set from Django settings (https://stripe.com/docs/api/checkout/sessions/create)?
- success_url path?
- cancel_url path?

And the following I think would need to become an argument of the function, which are passed from the API request:
- payment_method_types?
- mode?

**Comment by joshuakoh1** [comment]
Everything under _make_stripe_checkout_params should be checked against settings imo. For me I'll be using cancel/success url and payment method types.

Btw the trial period when using the days variable actually adds 1 less day.
