### ISSUE TITLE
Redirection in Custom CheckoutRequestSerializer

### ISSUE THREAD

**Issue by AxanIqbal** [oscarychen/drf-stripe-subscription#21]
can we have custom redirection option in the serializer the app to work with dynamic linking for mobile apps and website at same time ? or any way to do the platform checks and redirect according to the given platform

**Comment by oscarychen** [comment]
Not currently. Someone had suggested letting frontend application pass whatever redirect link as a url argument, I considered that as something that may potentially  open some opportunities for abuse unless implemented a whitelist checking mechanism on the backend.
