### ISSUE TITLE
Product Limit 100

### ISSUE THREAD

**Issue by pkrumins** [oscarychen/drf-stripe-subscription#22]
I'm considering using your library for Stripe payments but I noticed that when you pull products, you limit them to 100:

https://github.com/oscarychen/drf-stripe-subscription/blob/c352ec59944651a80a9ccbb7b26ea5cbc80b1e13/drf_stripe/stripe_api/products.py#L28

What is the reason you have hard coded this limit? How do I pull more than 100 products without modifying your code?

Thanks!

**Comment by oscarychen** [comment]
Hi there, this is actually due to a Stripe API having a max limit of 100 https://stripe.com/docs/api/products/list#list_products-limit, if unspecified it defaults to only 10. I intended to implement another layer of abstraction on the Stripe API that would retrieve all of your products in future.

**Comment by pkrumins** [comment]
Thanks Oscar!

**Comment by oscarychen** [comment]
I’ll re-open this issue at a future date when the limit is removed in a future update. For now just be mindful that this limit is there (hopefully you won’t need to have that many products).

**Comment by pkrumins** [comment]
Thanks for letting me know. I didn't know there was a 100 product limit total. Back in the day when Stripe moved from Subscriptions to Products, it converted each 1 Subscription to 1 Product. As a result, we have now 84 Products and I thought we will hit 100 soon.
