### ISSUE TITLE
Attach coupon to customer

### ISSUE THREAD

**Issue by joshuakoh1** [oscarychen/drf-stripe-subscription#26]
A callback to attach a coupon to a customer would be nice on:

1. Input passed on first creation of customer
2. Function on stripe_user that can be called manually

https://stripe.com/docs/billing/subscriptions/coupons?dashboard-or-api=api
https://stripe.com/docs/api/customers/update

**Comment by oscarychen** [comment]
Are you using the Stripe hosted Checkout? a customer can use coupon there when checking out.

**Comment by joshuakoh1** [comment]
@oscarychen It's different attaching a coupon to the customer vs letting them apply it themselves.

`If you provide a coupon code, the customer will have a discount applied on all recurring charges. Charges you create through the API will not have the discount.`
