### ISSUE TITLE
Stripe Models don't match stripe API

### ISSUE THREAD

**Issue by mtfurlan** [oscarychen/drf-stripe-subscription#34]
I tried to point this at our stripe test mode, and it threw a bunch of pydantic errors.
I made a list of what I had to change till it ran without errors.

I made the errors go away by changing stuff from `name type = None` or `name Optional[type]` to `name Optional[type] = None`

1. `StripePriceRecurring.aggregate_usage` can be `null`
2. `StripeCustomer` may be missing `sources`, `subscriptions`, `tax`, and `tax_ids`
3. `StripeSubscriptionItemsDataItem.billing_thresholds` may be `null`
3. `StripeSubscription.pending_setup_intent` may be `null`

**Comment by oscarychen** [comment]
- [ ] Update data model to handle null values
- [ ] Update test cases to test null values
- [ ] If tests now pass ok with pydantic v2, revert https://github.com/oscarychen/drf-stripe-subscription/commit/48c251dd6c49791125aa7cb84bc9428eb85b281d
