### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for StripePrices

### ISSUE THREAD

**Issue by geekynasir** [oscarychen/drf-stripe-subscription#38]
![image](https://github.com/oscarychen/drf-stripe-subscription/assets/60297068/1adac880-9d43-4774-ae01-3be63b2714c2)

**Comment by geekynasir** [comment]
I have only 1 subscription model in stripe. Any idea maybe im doing something wrong

**Comment by VinTurnier** [comment]
This is an issue with aggregate usage not being an optional type
file: drf_stripe/stripe_models/price.py 
current
`aggregate_usage: str = None`
new
`aggregate_usage: Optional[str] = None`
